[package]
name = "learnweb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "^0.3" }

[dependencies.async-std]
version = "1.9.0"
features = ["attributes"]

